services:
  web:
    build: .
    image: legal_api_openresty
    container_name: legal_api_openresty
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Mount application files for hot-reload during development
      - ./:/app:cached
    environment:
      - LAPIS_ENV=development
    working_dir: /app
    # Create .dockerjunk directory before starting nginx
    command: sh -c "mkdir -p /app/.dockerjunk/logs /app/.dockerjunk/client_body_temp /app/.dockerjunk/proxy_temp /app/.dockerjunk/fastcgi_temp /app/.dockerjunk/uwsgi_temp /app/.dockerjunk/scgi_temp && openresty -p /app/ -c nginx.conf"
